version: '2.2'

services:

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: artaeum
    ports:
      - 5432:5432

  mongodb:
    image: aashreys/mongo-auth:latest
    environment:
      AUTH: 'yes'
      MONGODB_ADMIN_USER: $MONGO_ADMIN_USER
      MONGODB_ADMIN_PASS: $MONGO_ADMIN_PASSWORD
      MONGODB_APPLICATION_USER: $MONGO_USER
      MONGODB_APPLICATION_PASS: $MONGO_PASSWORD
      MONGODB_APPLICATION_DATABASE: artaeum
    ports:
      - 27017:27017

  registry:
    image: egorrepnikov/artaeum-registry
    restart: always
    ports:
      - 8761:8761

  gateway:
    environment:
      GATEWAY_SERVICE_PASSWORD: $GATEWAY_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-gateway
    restart: always
    ports:
      - 8080:4000
    depends_on:
      - registry

  uaa:
    environment:
      EMAIL_ADDRESS: $EMAIL_ADDRESS
      EMAIL_PASSWORD: $EMAIL_PASSWORD
      MAIL_URL: $MAIL_URL
      POSTGRES_URL: $POSTGRES_URL
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      UAA_SERVICE_PASSWORD: $UAA_SERVICE_PASSWORD
      GATEWAY_SERVICE_PASSWORD: $GATEWAY_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-uaa
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgresql
      - registry

  profile:
    environment:
      POSTGRES_URL: $POSTGRES_URL
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      STORAGE_SERVICE_PASSWORD: $STORAGE_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-profile
    restart: always
    ports:
      - 6000:6000
    depends_on:
      - postgresql
      - registry

  storage:
    environment:
      STORAGE_SERVICE_PASSWORD: $STORAGE_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-storage
    restart: always
    ports:
      - 10000:10000
    depends_on:
      - registry

  blog:
    environment:
      MONGO_URI: $MONGO_URI
      STORAGE_SERVICE_PASSWORD: $STORAGE_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-blog
    restart: always
    ports:
      - 11000:11000
    depends_on:
      - mongodb
      - registry

  media:
    environment:
      MONGO_URI: $MONGO_URI
    image: egorrepnikov/artaeum-media
    restart: always
    ports:
      - 7000:7000
    depends_on:
      - mongodb
      - registry
