server.port: ${PORT:4000}

spring.application.name: gateway

security:
  oauth2:
    client:
      clientId: gateway
      clientSecret: ${GATEWAY_SERVICE_PASSWORD}
      accessTokenUri: ${OAUTH2_ACCESS_TOKEN_URI:http://uaa:5000/uaa/oauth/token}
      grant-type: client_credentials
      scope: client.user
    resource.user-info-uri: ${OAUTH2_USER_INFO_URI:http://uaa:5000/uaa/account/current}

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    nonSecurePort: ${HOSTPORT:${server.port}}
  client.serviceUrl.defaultZone: ${EUREKA_URL:http://registry:8761/eureka/}

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 101000

ribbon:
  ConnectTimeout: 25000
  ReadTimeout: 25000

zuul:
  ignoredServices: '*'
  sensitiveHeaders: Cookie,Set-Cookie
  host:
    connect-timeout-millis: 25000
    socket-timeout-millis: 25000
  routes:
    uaa:
      path: /uaa/**
      serviceId: uaa
      stripPrefix: false
    storage:
      path: /storage/**
      serviceId: storage
      stripPrefix: false
    blog:
      path: /blog/**
      serviceId: blog
      stripPrefix: false
    media:
      path: /media/**
      serviceId: media
      stripPrefix: false
    profile:
      path: /profile/**
      serviceId: profile
      stripPrefix: false
