version: '3.3'

services:

  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  mongodb:
    image: aashreys/mongo-auth:latest
    environment:
      AUTH: 'yes'
      MONGODB_ADMIN_USER: $MONGO_ADMIN_USER
      MONGODB_ADMIN_PASS: $MONGO_ADMIN_PASSWORD
      MONGODB_APPLICATION_USER: $MONGO_USER
      MONGODB_APPLICATION_PASS: $MONGO_PASSWORD
      MONGODB_APPLICATION_DATABASE: artaeum
    volumes:
      - ./data/mongodb/data/db:/data/db
  
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: artaeum
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data

  registry:
    image: egorrepnikov/artaeum-registry
    restart: always

  gateway:
    environment:
      GATEWAY_SERVICE_PASSWORD: $GATEWAY_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-gateway
    restart: always
    depends_on:
      - registry

  uaa:
    environment:
      EMAIL_ADDRESS: $EMAIL_ADDRESS
      EMAIL_PASSWORD: $EMAIL_PASSWORD
      MAIL_URL: $MAIL_URL
      POSTGRES_URL: $POSTGRES_URL
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      UAA_SERVICE_PASSWORD: $UAA_SERVICE_PASSWORD
      GATEWAY_SERVICE_PASSWORD: $GATEWAY_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-uaa
    restart: always
    depends_on:
      - postgresql
      - registry

  profile:
    environment:
      POSTGRES_URL: $POSTGRES_URL
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      STORAGE_SERVICE_PASSWORD: $STORAGE_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-profile
    restart: always
    depends_on:
      - postgresql
      - registry

  storage:
    environment:
      STORAGE_SERVICE_PASSWORD: $STORAGE_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-storage
    restart: always
    volumes:
      - ./data/storage/profile:/profile
      - ./data/storage/blog:/blog
    depends_on:
      - registry

  blog:
    environment:
      MONGO_URI: $MONGO_URI
      STORAGE_SERVICE_PASSWORD: $STORAGE_SERVICE_PASSWORD
    image: egorrepnikov/artaeum-blog
    restart: always
    depends_on:
      - mongodb
      - registry

  media:
    environment:
      MONGO_URI: $MONGO_URI
    image: egorrepnikov/artaeum-media
    restart: always
    depends_on:
      - mongodb
      - registry
